name: identity_card_scanning
description: Mobile App with API integration using dio client and Bloc-pattern state management. Project also includes text scanning from image using Google ML.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.4.0+1
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  google_ml_kit: ^0.7.0
  permission_handler: ^8.1.4+2
  fluttertoast: ^8.0.8
  image_watermark: ^0.0.5
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  qr_code_scanner: ^1.0.1
  esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
